### ISSUE TITLE
More intuitive printing of (symbolic) gates

### ISSUE THREAD

**Issue by amicciche** [QuantumSavory/QuantumClifford.jl#124]
When working with circuits, it would be nice to print the circuit with output like the following:
sCNOT(1,2)
sCNOT(3,4)
sHadamard(4)

The current style of output is very cumbersome and hard to work with (at least when working on the circuit level). For example:
 Symbolic two-qubit gate on qubit 3 and 13
X₁ ⟼ + XX
X₂ ⟼ + _X
Z₁ ⟼ + Z_
Z₂ ⟼ + ZZ
 Symbolic two-qubit gate on qubit 5 and 13
X₁ ⟼ + XX
X₂ ⟼ + _X
Z₁ ⟼ + Z_
Z₂ ⟼ + ZZ
 Symbolic two-qubit gate on qubit 7 and 13
X₁ ⟼ + XX
X₂ ⟼ + _X
Z₁ ⟼ + Z_
Z₂ ⟼ + ZZ
Having the option to reduce this output to 3 lines would be a very nice feature. Perhaps we can add a "print circuit" function?

**Comment by Krastanov** [comment]
@amicciche , should be fixed now. You can see the linked pull request for the changes (using `:typeinfo` to detect whether we are being printed inside of a print call for an array)
