### ISSUE TITLE
Quantikz support for ClassicalXOR gate

### ISSUE THREAD

**Issue by amicciche** [QuantumSavory/QuantumClifford.jl#181]
With the pull request I recently submitted, it would be nice for the new ClassicalXOR gate to be rendered in the circuit diagram, and for an error not to be thrown when you forget a ; in the REPL.

**Comment by Krastanov** [comment]
Sometime ago this was fixed. And a bit improved in #212 

`ClassicalXOR((1,2,3),5)`

![image](https://github.com/QuantumSavory/QuantumClifford.jl/assets/705248/ce058c47-b568-4b79-a878-c1d790852567)
