### ISSUE TITLE
Enhancing Issue Organization and Management with Label-Based Sorting

### ISSUE THREAD

**Issue by Fe-r-oz** [QuantumSavory/QuantumClifford.jl#273]
## Documentation
> #### Improvements or Additions to Documentation

- https://github.com/QuantumSavory/QuantumClifford.jl/issues/24
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/85
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/106
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/150
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/167
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/213
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/258

## Good First Issue
> #### Good For Newcomers

- https://github.com/QuantumSavory/QuantumClifford.jl/issues/14
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/24
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/45
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/82
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/97
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/106
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/131
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/135
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/137
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/140
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/147
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/150
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/151
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/167
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/178
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/179
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/190
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/191
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/192
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/208
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/213
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/214
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/215
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/216
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/217
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/218
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/242
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/258
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/260
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/261

## Performance Bug
> #### Something is unreasonably slow

- https://github.com/QuantumSavory/QuantumClifford.jl/issues/34
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/217
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/219
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/223
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/242

**Non-Clifford Functionality**
--

- https://github.com/QuantumSavory/QuantumClifford.jl/issues/199
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/200
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/201
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/202
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/203
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/260

## Enhancements
> #### New feature or request

- https://github.com/QuantumSavory/QuantumClifford.jl/issues/11
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/12
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/13
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/14
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/16
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/22
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/25
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/45
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/64
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/82
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/113
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/140
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/147
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/148
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/151
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/167
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/174
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/207

## Help Wanted
> #### Extra attention is needed

- https://github.com/QuantumSavory/QuantumClifford.jl/issues/140
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/147
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/148
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/207
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/208

## Bug
> #### Something isn't working

- https://github.com/QuantumSavory/QuantumClifford.jl/issues/190
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/191
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/208
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/245

## Code Quality
> #### Code that should be refactored

- https://github.com/QuantumSavory/QuantumClifford.jl/issues/42
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/113
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/114
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/131
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/135
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/137
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/177

## Experiment
> #### Experimental work

- https://github.com/QuantumSavory/QuantumClifford.jl/issues/168
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/175

## Compact
> #### Enable use of external project
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/14
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/16
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/147

## GPU
> #### Related to new GPU support edition

- https://github.com/QuantumSavory/QuantumClifford.jl/issues/165
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/166
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/168
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/173
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/174
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/175
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/176
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/177
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/178
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/179
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/220
- https://github.com/QuantumSavory/QuantumClifford.jl/issues/221

**Comment by Krastanov** [comment]
Thanks for looking into this, but I do not believe this issue is necessary. Github already provides this functionality by default in an automated manner with filtering (simply by opening the issues page and clicking on the label in question or entering a search query).
