### ISSUE TITLE
`inv` implementation for all subtypes of `AbstractCliffordOperator` [$200]

### ISSUE THREAD

**Issue by Krastanov** [QuantumSavory/QuantumClifford.jl#308]
<details>
<summary><strong>Bug bounty logistic details</strong> (click to expand)</summary>

To claim exclusive time to work on this bounty either post a comment here or message [skrastanov@umass.edu](mailto:skrastanov@umass.edu) with:

- your name
- github username
- **(optional)** a brief list of previous pertinent projects you have engaged in

Currently the project is claimed by `no one` until `...`.

If you want to, you can work on this project without making a claim, however claims are encouraged to give you and other contributors peace of mind. Whoever has made a claim takes precedence when solutions are considered.

You can always propose your own funded project, if you would like to contribute something of value that is not yet covered by an official bounty.
</details>

# Project: `inv` implementation for all subtypes of `AbstractCliffordOperator` [$200]

`LinearAlgebra.inv` already has methods defined for some of the types in this library meant to represent a Clifford operation. To obtain this bounty, you need to implement the missing `inv` methods for all other subtypes of `AbstractCliffordOperator`.

**Required skills**: Understanding of the Stabilizer state formalism.

**Reviewer**: Stefan Krastanov

**Duration**: 1 month

#### Payout procedure:

The Funding for these bounties comes from the National Science Foundation and from the NSF Center for Quantum Networks. The payouts are managed by the NumFOCUS foundation and processed in bulk once every two months. If you live in a country in which NumFOCUS can make payments, you can participate in this bounty program.

[Click here for more details about the bug bounty program.](https://github.com/QuantumSavory/.github/blob/main/BUG_BOUNTIES.md)

**Comment by Fe-r-oz** [comment]
I would be delighted to resolve this issue!

**Comment by Krastanov** [comment]
Sounds good! There is another issue that you currently have reserved, so I can not reserve this one too, but feel free to tackle it if you wish. For such situations without reservation you do not need to comment: feel free to just submit PRs.

**Comment by Krastanov** [comment]
duplicate of #286

finished in #332, #315, #314
