### ISSUE TITLE
Discrepancy in 2BGA `code_k` values when reproducing some results from paper by Lin et al via Hecke/Oscar.small_group

### ISSUE THREAD

**Issue by Fe-r-oz** [QuantumSavory/QuantumClifford.jl#391]
**Describe the bug 🐞**

The [paper](https://arxiv.org/pdf/2306.16400) that introduced 2BGA codes contains a wealth of abelian and non-abelian groups. For the sake of simplicity, this issue only refers to abelian groups.  Lin et al. used `GAP `for these calculations and defining group structures in the Table 1. `StructureDescription(SmallGroup(ℓ,#)) `from `GAP` was used by them. The documentation for [StructureDescription ](https://docs.gap-system.org/doc/ref/chap39.html#X87BF1B887C91CA2E) from `GAP`

**Spoiler**: This is related to 'dataset' size of `small_ group` between `Hecke` or `Oscar,` as both methods (`Hecke.small_group/Oscar.small_group`), provide isomorphic groups as seen from output of `describe(small_group(l, id))` but give different results for dimension `(code_k)`.  The small groups in `Oscar` go much further. To reiterate, the small groups have different forms but isomorphic as seen from output of `describe(small_group(l, id))`. **In the Spotlight**: @thofma, Thank you very much for your time. Please briefly a sentence or two about this phenomenon that came up recently in a discussion :)

The following cases give the correct values of `code_n,` and `code_k` with this new method of using `small_group` with a multiplication table, which is used by the authors.  The following cases are correctly produced. Here, # is the ID from the multiplication table when we use small_group. 

`[[72, 8, 9]] with l=36, # = 2 `

```julia
julia> using QuantumClifford
julia> using QuantumClifford.ECC
julia> using Hecke: group_algebra, small_group, dim, gens; using Nemo: GF;
julia> a_shifts = [0, 28]; b_shifts = [0, 9, 18, 12, 29, 14]; l=36; id = 2; 
# julia> describe(small_group(l, id))
# "C36" ✔
# Hecke.small_group and Oscar.small_group are isomorphic. 
julia> GA = group_algebra(GF(2), small_group(l, id));
julia> a = sum(GA[n%dim(GA)+1] for n in a_shifts);
julia> b = sum(GA[n%dim(GA)+1] for n in b_shifts);
julia> c = two_block_group_algebra_codes(a, b);
julia> code_n(c), code_k(c)
(72, 8) ✔ Table 1 (Block 1 Verified)
# with Oscar.small_group
# julia> code_n(c), code_k(c)
# (72, 2)
# code_n ✔
# code_k ✘ Expected 8

```
`[[54, 6, 9 ]] with l=27, # = 1  `

```julia
julia> using QuantumClifford
julia> using QuantumClifford.ECC
julia> using Hecke: group_algebra, small_group, dim, gens; using Nemo: GF;
julia> a_shifts = [0, 1, 3, 7]; b_shifts = [0, 1, 12, 19]; l=27; id = 1;
julia> GA = group_algebra(GF(2), small_group(l, id));
julia> a = sum(GA[n%dim(GA)+1] for n in a_shifts);
julia> b = sum(GA[n%dim(GA)+1] for n in b_shifts);
julia> c = two_block_group_algebra_codes(a, b);
julia> code_n(c), code_k(c)
(54, 6)  ✔ Table 1 (Block 3, Part 1 Verified)
# with Oscar.small_group
# julia> code_n(c), code_k(c)
# (54, 2)
# code_n ✔
# code_k ✘ Expected 6
```

These new methods are being introduced in https://github.com/QuantumSavory/QuantumClifford.jl/pull/390 as this functionality is not present for 2BGA. For more details about what `small_group` is, https://github.com/QuantumSavory/QuantumClifford.jl/pull/390#issuecomment-2411095431 and https://github.com/QuantumSavory/QuantumClifford.jl/pull/390#issuecomment-2411239628 can serve as useful starting point. Table 1 caption in the paper is the best place for information.

**Expected behavior 👇**

As seen from the MREs, `code_n `values are correctly calculated. But there is a small discrepancy in the `code_k` values.  The expectation is to have correct values of `code_k` to correctly reproduce the results from the paper.  To reiterate, Block 1 and Block 3 handles abelian groups only.

**Minimal Reproducible Example ⚠️**

As seen from all these 'abelian' cases (Block 1 and Block 3) of Table 1, the `code_n` values match exactly. But the `code_k` values have some variation. 

**MRE 1**

`[[60, 6, 10 ]] with l=30, # = 4 `

```julia
julia> using QuantumClifford
julia> using QuantumClifford.ECC
julia> using Hecke: group_algebra, small_group, dim, gens; using Nemo: GF;
julia> a_shifts = [0, 10, 6, 13]; b_shifts = [0, 25, 16, 12]; l=30; id = 4;
julia> GA = group_algebra(GF(2), small_group(l, id));
julia> a = sum(GA[n%dim(GA)+1] for n in a_shifts);
julia> b = sum(GA[n%dim(GA)+1] for n in b_shifts);
julia> c = two_block_group_algebra_codes(a, b);
julia> code_n(c), code_k(c)
(60, 2)

code_n ✔
code_k ✘ Expected 6

# with Oscar.small_group
# julia> code_n(c), code_k(c)
# (60, 4)
# code_n ✔
# code_k ✘ Expected 6
```

**MRE 2**

`[[70, 8, 10 ]] with l=35, # = 1 `

```julia
julia> using QuantumClifford
julia> using QuantumClifford.ECC
julia> using Hecke: group_algebra, small_group, dim, gens; using Nemo: GF;
julia> a_shifts = [0, 15, 16, 18]; b_shifts = [0, 1, 24, 27]; l=35; id = 1;
julia> GA = group_algebra(GF(2), small_group(l, id));
julia> a = sum(GA[n%dim(GA)+1] for n in a_shifts);
julia> b = sum(GA[n%dim(GA)+1] for n in b_shifts);
julia> c = two_block_group_algebra_codes(a, b);
julia> code_n(c), code_k(c)
(70, 2)

code_n  ✔
code_k ✘ Expected 8

# with Oscar.small_group
# julia> code_n(c), code_k(c)
# (70, 8)
# code_n ✔
# code_k ✔
```

**MRE 3**

`[[72, 8, 10 ]] with l=36, # = 2 `

```julia
julia> using QuantumClifford
julia> using QuantumClifford.ECC
julia> using Hecke: group_algebra, small_group, dim, gens; using Nemo: GF;
julia> a_shifts = [0, 9, 28, 31]; b_shifts = [0, 1, 21, 34]; l=36; id = 2;
julia> GA = group_algebra(GF(2), small_group(l, id));
julia> a = sum(GA[n%dim(GA)+1] for n in a_shifts);
julia> b = sum(GA[n%dim(GA)+1] for n in b_shifts);
julia> c = two_block_group_algebra_codes(a, b);
julia> code_n(c), code_k(c)
(72, 4)

code_n  ✔ 
code_k ✘ Expected 8

# with Oscar.small_group
# julia> code_n(c), code_k(c)
# (72, 6)
# code_n ✔
# code_k ✘ Expected 8
```

**MRE 4**

`[[72, 10, 9 ]] with l=36, # = 2 `

```julia
julia> using QuantumClifford
julia> using QuantumClifford.ECC
julia> using Hecke: group_algebra, small_group, dim, gens; using Nemo: GF;
julia> a_shifts = [0, 9, 28, 13]; b_shifts = [0, 1, 3, 22]; l=36; id = 2;
julia> GA = group_algebra(GF(2), small_group(l, id));
julia> a = sum(GA[n%dim(GA)+1] for n in a_shifts);
julia> b = sum(GA[n%dim(GA)+1] for n in b_shifts);
julia> c = two_block_group_algebra_codes(a, b);
julia> code_n(c), code_k(c)
(72, 6)

code_n  ✔
code_k ✘ Expected 10

# with Oscar.small_group
# julia> code_n(c), code_k(c)
# (72, 2)
# code_n ✔
# code_k ✘ Expected 10
```

**Error & Stacktrace or other complete output produced by the MRE ⚠️**

The error is the discrepancy in the code_k values.  There is no stacktrace. 

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Project QuantumClifford v0.9.11
  [861a8166] Combinatorics v1.0.2
  [864edb3b] DataStructures v0.18.20
  [ffbed154] DocStringExtensions v0.9.3
  [86223c79] Graphs v1.12.0
  [3e5b6fbb] HostCPUFeatures v0.1.17
⌅ [2cd5bd5f] ILog2 v0.2.4
  [1914dd2f] MacroTools v0.5.13
  [2edaba10] Nemo v0.47.1
  [aea7be01] PrecompileTools v1.2.1
  [5717a53b] QuantumInterface v0.3.6
  [fdea26ae] SIMD v3.6.0
  [8e1ec7a9] SumTypes v0.5.8
  [b77e0a4c] InteractiveUtils
  [37e2e46d] LinearAlgebra
  [9a3f8284] Random
  [2f01184e] SparseArrays v1.10.0
  [10745b16] Statistics v1.10.0
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated`
```

  - Output of `using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)`

```julia
julia> using Pkg; Pkg.status(; mode = PKGMODE_MANIFEST)

Project QuantumClifford v0.9.11
Status ...
  [c3fe647b] AbstractAlgebra v0.43.6
  [ec485272] ArnoldiMethod v0.4.0
  [62783981] BitTwiddlingConvenienceFunctions v0.1.6
  [861a8166] Combinatorics v1.0.2
  [f70d9fcc] CommonWorldInvalidations v1.0.0
  [34da2185] Compat v4.16.0
  [864edb3b] DataStructures v0.18.20
  [ffbed154] DocStringExtensions v0.9.3
  [86223c79] Graphs v1.12.0
  [3e5b6fbb] HostCPUFeatures v0.1.17
⌅ [2cd5bd5f] ILog2 v0.2.4
  [615f187c] IfElse v0.1.1
  [d25df0c9] Inflate v0.1.5
  [692b3bcd] JLLWrappers v1.6.1
  [1914dd2f] MacroTools v0.5.13
  [2edaba10] Nemo v0.47.1
  [bac558e1] OrderedCollections v1.6.3
  [aea7be01] PrecompileTools v1.2.1
  [21216c6a] Preferences v1.4.3
  [5717a53b] QuantumInterface v0.3.6
  [fb686558] RandomExtensions v0.4.4
  [fdea26ae] SIMD v3.6.0
  [699a6c99] SimpleTraits v0.9.4
  [aedffcd0] Static v1.1.1
  [90137ffa] StaticArrays v1.9.7
  [1e83bf80] StaticArraysCore v1.4.3
  [8e1ec7a9] SumTypes v0.5.8
  [e134572f] FLINT_jll v300.100.300+0
⌅ [656ef2d0] OpenBLAS32_jll v0.3.24+0
  [0dad84c5] ArgTools v1.1.1
  [56f22d72] Artifacts
  [2a0f44e3] Base64
  [ade2ca70] Dates
  [8ba89e20] Distributed
  [f43a241f] Downloads v1.6.0
  [7b1f6079] FileWatching
  [b77e0a4c] InteractiveUtils
  [b27032c2] LibCURL v0.6.4
  [76f85450] LibGit2
  [8f399da3] Libdl
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [d6f4376e] Markdown
  [a63ad114] Mmap
  [ca575930] NetworkOptions v1.2.0
  [44cfe95a] Pkg v1.10.0
  [de0858da] Printf
  [3fa0cd96] REPL
  [9a3f8284] Random
  [ea8e919c] SHA v0.7.0
  [9e88b42a] Serialization
  [1a1011a3] SharedArrays
  [6462fe0b] Sockets
  [2f01184e] SparseArrays v1.10.0
  [10745b16] Statistics v1.10.0
  [fa267f1f] TOML v1.0.3
  [a4e569a6] Tar v1.10.0
  [8dfed614] Test
  [cf7118a7] UUIDs
  [4ec0a83e] Unicode
  [e66e0078] CompilerSupportLibraries_jll v1.1.1+0
  [781609d7] GMP_jll v6.2.1+6
  [deac9b47] LibCURL_jll v8.4.0+0
  [e37daf67] LibGit2_jll v1.6.4+0
  [29816b5a] LibSSH2_jll v1.11.0+1
  [3a97d323] MPFR_jll v4.2.0+1
  [c8ffd9c3] MbedTLS_jll v2.28.2+1
  [14a3606d] MozillaCACerts_jll v2023.1.10
  [4536629a] OpenBLAS_jll v0.3.23+4
  [bea87d4a] SuiteSparse_jll v7.2.1+1
  [83775a58] Zlib_jll v1.2.13+1
  [8e850b90] libblastrampoline_jll v5.8.0+1
  [8e850ede] nghttp2_jll v1.52.0+1
  [3f19e933] p7zip_jll v17.4.0+2
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
```

  - Output of `versioninfo()`

```julia
julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 4 × Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, skylake)
Threads: 1 default, 0 interactive, 1 GC (on 4 virtual cores)
```

**Comment by thofma** [comment]
Can you explain where the `a_shifts` and `b_shifts` are coming from, or what is this supposed to be in reference to the paper? Lets stick to the first example
```
julia> using QuantumClifford
julia> using QuantumClifford.ECC
julia> using Hecke: group_algebra, small_group, dim, gens; using Nemo: GF;
julia> a_shifts = [0, 28]; b_shifts = [0, 9, 18, 12, 29, 14]; l=36; id = 2; 
```
Are they coming from Table I?

**Comment by Fe-r-oz** [comment]
Sorry for the late response.  I was taking a nap. I am going to explain it now.

Yup. The examples refer to the Block 1 and Block 3 of the Table 1. So in this example:

> `a_shifts = [0, 28]; b_shifts = [0, 9, 18, 12, 29, 14]; l=36; id = 2; `

`a` and `b` are terms of the group algebra element that is constructed by  `GA = group_algebra(GF(2), small_group(l, id));`
where Lin and Pryadko use the `GAP` `SmallGroup(36, 2)` which corresponds to `Hecke.small_group(36, 2)` - both have same structure  `C36`.

This is the first example of the Table 1, Block 1  where `a = 1+ r^28`, and  `b = 1 +  r^9 +  r^18 + r^12 +  r^29 + r^14`.

I will get back to my PC, and give two examples of the first case.

A slight irrelevant detail: I have reproduced all the codes from `Table 2` of this paper.

**Comment by Fe-r-oz** [comment]
`Method 1:`

```
julia> using QuantumClifford
julia> using QuantumClifford.ECC
julia> using Hecke: group_algebra, small_group, dim, gens; using Nemo: GF;
julia> GA = group_algebra(GF(2), abelian_group(36));
julia> r = gens(GA)[1]; # element of group algebra, only 1 generator.
julia> A = reshape([1 + r^28], (1, 1));
julia> B = reshape([1 + r^9 + r^18 + r^12 + r^29 + r^14], (1, 1));
julia> c = LPCode(A,B);
julia> code_n(c), code_k(c)
(72, 8)
```


`Method 2:` This is similar to `a_shifts` and `b_shifts` as vector route: 
```
julia> using QuantumClifford
julia> using QuantumClifford.ECC
julia> using Hecke: group_algebra, small_group, dim, gens; using Nemo: GF;
julia> code_n(generalized_bicycle_codes([0 , 28], [0 ,9, 18, 12, 29, 14], 36)), code_k(generalized_bicycle_codes([0 , 28], [0 ,9, 18, 12, 29, 14], 36))
(72, 8)
```

These two method provide the same results for length and dimension,` (72, 8)`
Also, under the hood of `generalized_bicycle_codes`, is:

```
function generalized_bicycle_codes(...)
julia> GA = group_algebra(GF(2), abelian_group(l));
julia> a = sum(GA[n%dim(GA)+1] for n in a_shifts);
julia> b = sum(GA[n%dim(GA)+1] for n in b_shifts);
julia> c = two_block_group_algebra_codes(a, b);
```

The small variation in `code_k` happens when `small_group(36,2))` is used like in the first example: ` GA = group_algebra(GF(2), Hecke/Oscar.small_group(36, 2))`.

**Comment by thofma** [comment]
There is some misunderstanding. Using things like `a_shifts` to redo the computations in the paper are not the right approach. The construction in the paper relies on a very specific presentation of the group described in the respective column. Using any other presentation of the group or generators will yield different results. For example,
```
julia> G = Oscar.small_group(36, 2)
Pc group of order 36

julia> gens(G)
4-element Vector{PcGroupElem}:
 f1
 f2
 f3
 f4

julia> collect(G)
36-element Vector{PcGroupElem}:
[...]
```
shows that this specific presentation of cyclic group $C_{36}$ is given by 4 generators, so incompatible with the presentation $C_{36} \cong \langle r | r^{36} \rangle$ in the paper. It is the same for all the other groups. That you sometimes get the right results is pure coincidence. Just create the groups and group algebra elements as they are given in paper. Here is an example for the second group from Table I and the construction of $b$:
```
julia> F = free_group(["r", "s"]);

julia> r, s = gens(F);

julia> G, = quo(F, [s^4, r^9, s^(-1)*r*s*r]);

julia> describe(G)
"C9 : C4"

julia> small_group_identification(G)
(36, 1)

julia> F2G = group_algebra(GF(2), G);

julia> r, s = gens(G); # for less typing

julia> b_elts = [one(G), s, r^6, s^3 * r, s * r^7, s^3 * r^5];

julia> b = sum(F2G(x) for x in b_elts);
```

By the way, the presentation for this group is wrong in Table I. It must be $r^9$ instead of $r^6$.

**Comment by Fe-r-oz** [comment]
This absolutely makes sense! Exactly, the presentation is very specific and it should not be ignored like what I was doing...  Yup, the second row has $r^6$ but the 10th row has $r^9$ for the same structure, seems like a typo from them.  But I will check each presentation just to be sure. Thank you for the heads-up!

I had given presentation consideration in https://github.com/QuantumSavory/QuantumClifford.jl/pull/382 but should not have overlooked it in later PRs... My bad. 

Thank you so much!

**Comment by Fe-r-oz** [comment]
This is resolved! All the cases mentioned here have been verified.

Thank you once again, Tommy, for your valuable insights! You truly shone in the spotlight.
